# Generated by Django 3.1.4 on 2021-01-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('edit_all_users', 'Can edit any user'), ('edit_username', "Can edit a user's username"), ('edit_department', 'Can assign a user to a department'), ('edit_staff_status', "Can edit a user's staff status"), ('view_phone_number', "Can view a user's phone number"), ('view_advanced_acc_info', 'Can view more administrative information about an account')]},
        ),
    ]
