# Generated by Django 3.1.4 on 2021-01-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_auth', '0002_auto_20201230_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='The name of the department', max_length=128, unique=True),
        ),
    ]
