# Generated by Django 3.1.4 on 2020-12-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='history_log',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_items',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status_history',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='service_items',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='status_history',
        ),
        migrations.AddField(
            model_name='status',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='carbina.job'),
            preserve_default=False,
        ),
    ]
