# Generated by Django 3.1 on 2020-10-20 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carbina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_requested', to='carbina.service'),
        ),
        migrations.AddField(
            model_name='quote',
            name='status_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='carbina.status'),
        ),
        migrations.AddField(
            model_name='jobpicture',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_pictures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='history_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_log', to='carbina.historylogupdate'),
        ),
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='carbina.jobpicture'),
        ),
        migrations.AddField(
            model_name='job',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='carbina.quote'),
        ),
        migrations.AddField(
            model_name='job',
            name='service_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='carbina.service'),
        ),
        migrations.AddField(
            model_name='job',
            name='status_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_status_history', to='carbina.status'),
        ),
        migrations.AddField(
            model_name='client',
            name='job_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='carbina.job'),
        ),
        migrations.AddField(
            model_name='client',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='carbina.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='quote_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='carbina.quote'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
