# Generated by Django 3.1.4 on 2021-01-15 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbina', '0003_auto_20210101_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='carbina.quote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
