# Generated by Django 3.1 on 2020-10-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbina', '0004_auto_20201028_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='job_list',
        ),
        migrations.RemoveField(
            model_name='client',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='client',
            name='quote_list',
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='carbina.client'),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='carbina.client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='carbina.client'),
        ),
    ]
