# Generated by Django 3.1.4 on 2021-01-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbina', '0005_auto_20210115_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_view_contact_info', "Can view client's contact information"), ('can_list_all_clients', 'Can view a list of all clients')], 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'get_latest_by': 'scheduled_time', 'ordering': ['-scheduled_time', 'title'], 'permissions': [('can_view_price', "Can view each item's estimated price"), ('can_edit_price', "Can edit each item's estimated price"), ('can_view_all_quotes', 'Can view any quote regardless of assignment')]},
        ),
    ]
