# Generated by Django 3.1.4 on 2020-12-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbina', '0005_auto_20201029_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
