# Generated by Django 3.1.4 on 2020-12-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbina', '0006_auto_20201229_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='static_map',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
